// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTQ-VfHW3jVvblrF0Q3nwe4DI7KYaUJKQ',
    appId: '1:85482011700:web:73cae39f1c7e895938de61',
    messagingSenderId: '85482011700',
    projectId: 'studmall2',
    authDomain: 'studmall2.firebaseapp.com',
    storageBucket: 'studmall2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA0i-PVeHwli_89M2pbx9qZGof3L7TKSc',
    appId: '1:85482011700:android:04183ce36d96d5a238de61',
    messagingSenderId: '85482011700',
    projectId: 'studmall2',
    storageBucket: 'studmall2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfaa9E2-Kmxt7GVz9_g-IO69lFcPr2mBk',
    appId: '1:85482011700:ios:74dd5fbd4e8e875c38de61',
    messagingSenderId: '85482011700',
    projectId: 'studmall2',
    storageBucket: 'studmall2.firebasestorage.app',
    iosBundleId: 'com.example.studmall2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfaa9E2-Kmxt7GVz9_g-IO69lFcPr2mBk',
    appId: '1:85482011700:ios:74dd5fbd4e8e875c38de61',
    messagingSenderId: '85482011700',
    projectId: 'studmall2',
    storageBucket: 'studmall2.firebasestorage.app',
    iosBundleId: 'com.example.studmall2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTQ-VfHW3jVvblrF0Q3nwe4DI7KYaUJKQ',
    appId: '1:85482011700:web:9b9738330db9cfc138de61',
    messagingSenderId: '85482011700',
    projectId: 'studmall2',
    authDomain: 'studmall2.firebaseapp.com',
    storageBucket: 'studmall2.firebasestorage.app',
  );
}
